[workspace]
authors = ["windiana42 <windiana@users.sf.net>"]
channels = ["conda-forge"]
name = "example"
platforms = ["osx-arm64", "osx-64", "linux-aarch64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pydiverse-pipedag = ">=0.12.0,<0.13"
pydot = ">=4.0.1,<5"
