[workspace]
authors = ["windiana42 <windiana@users.sf.net>"]
channels = ["conda-forge"]
name = "example"
platforms = ["osx-arm64", "osx-64", "linux-aarch64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
pydiverse-pipedag = ">=0.10.9,<0.11"
pydot = ">=4.0.1,<5"
# dependencies for s3 functionalities
s3fs = ">=2025.5.1,<2026"
boto3 = ">=1.38.13,<2"
# dependency for ZooKeeperLockManager (alternatives: FileLockManager, NoLockManager)
kazoo = ">=2.8.0"
# optional dependency for using pydiverse-transform (pdt.Table)
pydiverse-transform = ">=0.5.2,<0.6"
# optional dependency for dataframely schema classes
dataframely = ">=1.2.1,<2"
# optional dependency for colspec classes (same as dataframely but with SQL support)
pydiverse-colspec = ">=0.2.4,<0.3"
# independent library used in realistic_pipeline.py
xgboost = ">=3.0.2,<4"
# this could be installed in separate environment simply for running docker-compose
docker-compose = ">=2.39.1,<3"
